key_map = {
    "NameRegistered": "",
    "RegNumber": "",
    "RegNumberOther": "",
    "ValuationDate": "",
    "EndDate": "",
    "C003": "",
    "F006": "",
    "F0065": "",
    "F0067": "",
    "F0063": "",
    "F0062": "",
    "F0064": "",
    "F0066": "",
    "F006Other": "",
    "Per1.1": "",
    "Per2.1": "",
    "Per3.1": "",
    "Per4.1": "",
    "Per1.2": "",
    "Per2.2": "",
    "Per3.2": "",
    "Per4.2": "",
    "Per1.3": "",
    "Per2.3": "",
    "Per3.3": "",
    "Per4.3": "",
    "Per1.4": "",
    "Per2.4": "",
    "Per3.4": "",
    "Per4.4": "",
    "Per1.8": "",
    "Per2.8": "",
    "Per1.5": "",
    "Per1.6": "",
    "Per1.7": "",
    "Per1.9": "",
    "Per1.10": "",
    "Per2.5": "",
    "Per2.6": "",
    "Per2.7": "",
    "Per2.9": "",
    "Per2.10": "",
    "Per3.5": "",
    "Per3.6": "",
    "Per3.7": "",
    "Per3.8": "",
    "Per3.9": "",
    "Per3.10": "",
    "Per4.5": "",
    "Per4.6": "",
    "Per4.7": "",
    "Per4.8": "",
    "Per4.9": "",
    "Per4.10": "",
    "Per1.11": "",
    "Per2.11": "",
    "Per3.11": "",
    "Per4.11": "",
    "NumberMembers": "",
    "AverageAge": "",
    "AverageService": "",
    "AverageSalary": "",
    "AveragePension": "",
    "NumberMembers2": "",
    "AverageAge2": "",
    "AveragePension2": "",
    "NumberMembers3": "",
    "AverageAge3": "",
    "AveragePension3": "",
    "I020": "",
    "I20other": "",
    "I021": "",
    "I21other": "",
    "032a": "",
    "032b": "",
    "032c": "",
    "032d": "",
    "032e": "",
    "032f": "",
    "032g": "",
    "032h": "",
    "032i": "",
    "InitialRate": "",
    "NumYears": "",
    "UltimateRate": "",
    "InitialRate2": "",
    "NumYears2": "",
    "UltimateRate2": "",
    "InitialRate3": "",
    "NumYears3": "",
    "UltimateRate3": "",
    "InitialRate4": "",
    "NumYears4": "",
    "UltimateRate4": "",
    "InitialRate5": "",
    "NumYears5": "",
    "UltimateRate5": "",
    "InitialRate6": "",
    "NumYears6": "",
    "UltimateRate6": "",
    "InitialRate7": "",
    "NumYears7": "",
    "UltimateRate7": "",
    "035": "",
    "I036": "",
    "I036Other": "",
    "I036a": "",
    "I036ai": "",
    "l036aii": "",
    "I036aiii": "",
    "I036aiiiOther": "",
    "I036bi": "",
    "I036biim": "",
    "I036biif": "",
    "I037_includ": "",
    "I037_sep": "",
    "I037_no": "",
    "I038ai": "",
    "I038ae": "",
    "I038aei": "",
    "I038bi": "",
    "I038be": "",
    "I038bei": "",
    "I039": "",
    "I040": "",
    "I041": "",
    "RetAge": "",
    "K064dOther": "",
    "K064a": "",
    "K064b": "",
    "K064c": "",
    "K064d": "",
    "K070": "",
    "K071": "",
    "K072": "",
    "K080": "",
    "K081": "",
    "K082": "",
    "K090": "",
    "K091": "",
    "K092": "",
    "K093": "",
    "K094bOther": "",
    "K094a": "",
    "K094b": "",
    "K100": "",
    "Jini": "",
    "SelectPer1": "",
    "JUltimateRate4": "",
    "Jini2": "",
    "SelectPer2": "",
    "JUltimateRate5": "",
    "Jini3": "",
    "SelectPer3": "",
    "JUltimateRate6": "",
    "Jini4": "",
    "SelectPer4": "",
    "JUltimateRate7": "",
    "J049ml": "",
    "J049mlOther": "",
    "J049ma": "",
    "J049maOther": "",
    "J049il": "",
    "J049ilOther": "",
    "J049ia": "",
    "J049iaOther": "",
    "K050": "",
    "K051": "",
    "K052": "",
    "K053": "",
    "K060": "",
    "K061": "",
    "K062": "",
    "K063": "",
    "K101": "",
    "K107": "",
    "K102": "",
    "K103": "",
    "ChangePer": "",
    "ChangeAmt": "",
    "ChangeAmth": "",
    "ChangePer1": "",
    "ChangeAmt1": "",
    "ChangeAmth1": "",
    "ChangePer2": "",
    "ChangeAmt2": "",
    "ChangeAmth2": "",
    "L110": "",
    "L111Date": "",
    "L111": "",
    "L112": "",
    "L113": "",
    "L114": "",
    "L115": "",
    "L116": "",
    "L117": "",
    "L118": "",
    "L119": "",
    "L120": "",
    "L121": "",
    "L122": "",
    "L123": "",
    "L124": "",
    "L125Text": "",
    "L125": "",
    "L126Text": "",
    "L126": "",
    "L127": "",
    "M135": "",
    "M136": "",
    "M136a": "",
    "O1392aPer1": "",
    "O1392aSpe": "",
    "O1392bPer1": "",
    "O1392bSpe": "",
    "O1392cPer1": "",
    "O1392cSpe": "",
    "O1392dPer1": "",
    "O1392dSpe": "",
    "O1395": "",
    "O1396": "",
    "O1397": "",
    "O1398": "",
    "O1399c": "",
    "O1399d": "",
    "O137": "",
    "O138a": "",
    "O138b": "",
    "O138c": "",
    "O138d": "",
    "O138e": "",
    "O138ei": "",
    "O138eii": "",
    "O138eiii": "",
    "O138eiv": "",
    "O1391": "",
    "O1391i": "",
    "O1392aPer2": "",
    "O1392bPer2": "",
    "O1392cPer2": "",
    "O1392dPer2": "",
    "O1392aPer3": "",
    "O1392bPer3": "",
    "O1392cPer3": "",
    "O1392dPer3": "",
    "O1392aPer4": "",
    "O1392bPer4": "",
    "O1392cPer4": "",
    "O1392dPer4": "",
    "O1393": "",
    "O1394": "",
    "O1399a": "",
    "O1399b": "",
    "O1408aPer1": "",
    "O1408aPer2": "",
    "O1408aPer3": "",
    "O1408aPer4": "",
    "O1408aSpe": "",
    "O1408bPer1": "",
    "O1408bPer2": "",
    "O1408bPer3": "",
    "O1408bPer4": "",
    "O1408bSpe": "",
    "O1401a": "",
    "O1401b": "",
    "O1401c": "",
    "O1401d": "",
    "O1401e": "",
    "O1402": "",
    "O1403Date": "",
    "O1404": "",
    "O1405": "",
    "O1406": "",
    "O1407": "",
    "O141": "",
    "O142": "",
    "O144.(i)": "",
    "O144.(ii)": "",
    "0144.i.a": "",
    "0144.ii.a": "",
    "0144.ii.b": "",
    "P145": "",
    "P146": "",
    "P147": "",
    "P148": "",
    "P149": "",
    "P149a": "",
    "R173": "",
    "R173a": "",
    "R173b": "",
    "R174a": "",
    "R174b": "",
    "R175i": "",
    "R1755ii": "",
    "R175iii": "",
    "R175iv": "",
    "R176a": "",
    "R176b": "",
    "R177a": "",
    "R177bi": "",
    "R177bii": "",
    "R177biii": "",
    "R177biv": "",
    "R178": "",
    "S185": "",
    "S186": "",
    "S187": "",
    "S188": "",
    "S189": "",
    "S190": "",
    "S191": "",
    "T192": "",
    "T193": "",
    "T193b": "",
    "T193c": "",
    "T193d": "",
    "T193e": "",
    "T194a": "",
    "T194ab": "",
    "T194ac": "",
    "T194ad": "",
    "T194ae": "",
    "T194b": "",
    "T194bb": "",
    "T194bc": "",
    "T194bd": "",
    "T194be": "",
    "T195": "",
    "T196": "",
    "T196a": "",
    "T196b": "",
    "T194c": "",
    "T197": "",
    "T197a": "",
    "T197b": "",
    "T197c": "",
    "T198a": "",
    "T198ab": "",
    "T198ac": "",
    "T198ad": "",
    "T198ae": "",
    "T198b": "",
    "T198bb": "",
    "T198bc": "",
    "T198bd": "",
    "T198be": "",
    "Signatureactuary": "",
    "U199": "",
    "U200": "",
    "U200a": "",
    "U200b": "",
    "U200c": "",
    "U201": "",
    "U201a": "",
    "U201b": "",
    "U201c": "",
    "U202a2": "",
    "U202a3": "",
    "U202a4": "",
    "U202b": "",
    "U202a": "",
    "U202a1": "",
    "U203b": "",
    "U203b1": "",
    "U202b1": "",
    "U203b2": "",
    "U202b3": "",
    "U202b4": "",
    "U203a2": "",
    "U203a4": "",
    "U203a": "",
    "U204b": "",
    "U203a3": "",
    "U204a": "",
    "U204a1": "",
    "U204a2": "",
    "U204a3": "",
    "U204a4": "",
    "U203a1": "",
    "U204b1": "",
    "U204b2": "",
    "U204b3": "",
    "U204be": "",
    "Datedthisday": "",
    "Datedthismonth": "",
    "Datedthisyear": "",
    "PrintNAme": "",
    "NameFirm": "",
    "telephone": "",
    "EmailAddress": ""
}

field_names = [
    "pension plan name",
    "registration number",
    "other registration number",
    "valuation date start beginning",
    "end date",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "period 1 start date beginning",
    "period 2 start date beginning",
    "period 3 start date beginning",
    "period 4 start date beginning",
    "period 1 end date",
    "period 2 end date",
    "period 3 end date",
    "period 4 end date",
    "period 1 normal cost defined benefit provision members",
    "period 2 normal cost defined benefit provision members",
    "period 3 normal cost defined benefit provision members",
    "period 4 normal cost defined benefit provision members",
    "period 1 normal cost defined benefit provision employer",
    "period 2 normal cost defined benefit provision employer",
    "period 3 normal cost defined benefit provision employer",
    "period 4 normal cost defined benefit provision employer",
    "period 1 special payments for going concern unfunded liability and solvency deficiency employer",
    "period 2 special payments for going concern unfunded liability and solvency deficiency employer",
    "period 1 normal cost defined benefit provision explicit expense allowance",
    "period 1 normal cost money purchase provision members",
    "period 1 normal cost money purchase provision employer",
    "period 1 special payments for going concern unfunded liability and solvency deficiency members",
    "period 1 fixed contributions employer and member defined benefit provision",
    "period 2 normal cost defined benefit provision explicit expense allowance",
    "period 2 normal cost money purchase provision members",
    "period 2 normal cost money purchase provision employer",
    "period 2 special payments for going concern unfunded liability and solvency deficiency members",
    "period 2 fixed contributions employer and member defined benefit provision",
    "period 3 normal cost defined benefit provision explicit expense allowance",
    "period 3 normal cost money purchase provision members",
    "period 3 normal cost money purchase provision employer",
    "period 3 special payments for going concern unfunded liability and solvency deficiency employer",
    "period 3 special payments for going concern unfunded liability and solvency deficiency members",
    "period 3 fixed contributions employer and member defined benefit provision",
    "period 4 normal cost defined benefit provision explicit expense allowance",
    "period 4 normal cost money purchase provision members",
    "period 4 normal cost money purchase provision employer",
    "period 4 special payments for going concern unfunded liability and solvency deficiency employer",
    "period 4 special payments for going concern unfunded liability and solvency deficiency members",
    "period 4 fixed contributions employer and member defined benefit provision",
    "period 1 fixed contributions employer and member money purchase provision",
    "period 2 fixed contributions employer and member money purchase provision",
    "period 3 fixed contributions employer and member money purchase provision",
    "period 4 fixed contributions employer and member money purchase provision",
    "number of active members",
    "active members average age",
    "active members average pensionable service",
    "active members average salary",
    "active members average annual pension",
    "number of retired members",
    "retired members average age",
    "retired members average annual pension",
    "number of other members",
    "other members average age",
    "other members average annual pension",
    "",
    "",
    "",
    "",
    "going concern expected investment return on plan assets",
    "going concern expected additional return from active investment management",
    "going concern expenses paid from fund for active investment management",
    "going concern expected investment expenses",
    "going concern other expected expenses including administrative expenses",
    "going concern effect of rebalancing and diversification",
    "going concern margins for adverse deviations",
    "going concern other components",
    "going concern net going concern valuation interest discount rate",
    "*",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "*",
    "year income tax regulations maximum pension limit escalation commences",
    "mortality table",
    "mortality table other",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "assumed retirement age",
    "going concern liabilities reserves other",
    "going concern liabilities reserves expenses",
    "going concern liabilities reserves ad hoc indexing",
    "going concern liabilities reserves provision for adverse deviations",
    "going concern liabilities reserves other",
    "net funded position surplus diversification",
    "additional voluntary contributions",
    "money purchase assets",
    "solvency assets with adjustment for expense provision",
    "solvency assets amount of wind up expense provision",
    "solvency assets optional ancillary contributions account balance included in solvency assets for a flexible pension plan",
    "solvency liabilities for active members",
    "solvency liabilities for retired members",
    "solvency liabilities for other participants",
    "solvency liabilities for optional ancillary benefits under a flexible pension plan",
    "solvency liabilities reserves other",
    "solvency liabilities reserves expenses",
    "solvency liabilities reserves other",
    "net solvency position surplus deficit",
    "benefits to be settled by lump sum transfer initial rate",
    "benefits to be settled by lump sum transfer select period",
    "benefits to be settled by lump sum transfer ultimate rate",
    "benefits to be settled by purchase of deferred annuity initial rate",
    "benefits to be settled by purchase of deferred annuity select period",
    "benefits to be settled by purchase of deferred annuity ultimate rate",
    "benefits to be settled by purchase of immediate annuity initial rate",
    "benefits to be settled by purchase of immediate annuity select period",
    "benefits to be settled by purchase of immediate annuity ultimate rate",
    "*",
    "*",
    "*",
    "mortality table lump sum",
    "mortality table lump sum other",
    "mortality table annuity purchase",
    "mortality table annuity purchase other",
    "improvement scale lump sum",
    "improvement scale lump sum other",
    "improvement scale annuity purchase",
    "improvement scale annuity purchase other",
    "market value of assets adjusted for receivables and payables",
    "amount of contributions receivable included in market value",
    "going concern assets",
    "going concern optional ancillary contributions account balance for flexible pension plan",
    "going concern liabilities active members",
    "going concern liabilities retired members",
    "going concern liabilities other participants",
    "going concern liabilities optional ancillary benefits flexible pension plan",
    "solvency liabilities incremental cost",
    "duration of liabilities assumed to be settled through the purchase of annuities",
    "",
    "",
    "1% lower discount rate going concern liabilities change in percentage",
    "1% lower discount rate going concern liabilities change in amount",
    "1% higher discount rate going concern liabilities change in amount",
    "1% lower discount rate normal cost change in percentage",
    "1% lower discount rate normal cost change in amount",
    "1% higher discount rate normal cost change in amount",
    "1% lower discount rate solvency liabilities change in percentage",
    "1% lower discount rate solvency liabilities change in amount",
    "1% higher discount rate solvency liabilities change in amount",
    "",
    "date of last filed funding valuation report",
    "net funded position as of last filed funding valuation report",
    "actuarial gain or loss due to interest on surplus unfunded liability",
    "actuarial gain or loss due to special payments",
    "actuarial gain or loss due to amount used for contribution holiday",
    "actuarial gain or loss due to change in actuarial assumptions",
    "actuarial gain or loss due to change in asset valuation method",
    "actuarial gain or loss due to change in liability valuation method",
    "actuarial gain or loss due to plan amendments changes",
    "actuarial gain or loss due to investment experience",
    "actuarial gain or loss due to retirement experience",
    "actuarial gain or loss due to mortality experience",
    "actuarial gain or loss due to withdrawal experience",
    "actuarial gain or loss due to salary increase experience",
    "actuarial gain or loss due to optional ancillary contributions forfeited",
    "*",
    "*",
    "*",
    "*",
    "*",
    "",
    "",
    "",
    "period 1 special payments going concern unfunded liability members",
    "going concern unfunded liability members present value of special payments",
    "period 1 special payments going concern unfunded liability employer",
    "going concern unfunded liability employer present value of special payments",
    "period 1 special payments plan amendment members",
    "going concern unfunded liability plan amendment members present value of special payments",
    "period 1 special payments plan amendment employer",
    "going concern unfunded liability plan amendment employer present value of special payments",
    "provision for adverse deviations combined target asset allocation for fixed income assets",
    "provision for adverse deviations duration of going concern liabilities",
    "provision for adverse deviations total pfad",
    "provision for adverse deviations amount of pfad included in normal cost",
    "provision for adverse deviations future escalated adjustments going concern liability",
    "provision for adverse deviations future escalted adjustments normal cost",
    "",
    "going concern total asset value of buy in annuity",
    "going concern total liabilities buy in annuity",
    "going concern total asset value non discharged buy out annuity",
    "going concern total liabilities non discharged buy out annuity",
    "",
    "annuity transactions made",
    "total premium of buy out annuity",
    "going concern liabilities annuity discharge",
    "top up contributions",
    "",
    "available actuarial surplus",
    "period 2 special payments going concern unfunded liability members",
    "period 2 special payments going concern unfunded liability employer",
    "period 2 special payments plan amendment members",
    "period 2 special payments plan amendment employer",
    "period 3 special payments going concern unfunded liability members",
    "period 3 special payments going concern unfunded liability employer",
    "period 3 special payments plan amendment members",
    "period 3 special payments plan amendment employer",
    "period 4 special payments going concern unfunded liability members",
    "period 4 special payments going concern unfunded liability employer",
    "period 4 special payments plan amendment members",
    "period 4 special payments plan amendment employer",
    "",
    "",
    "",
    "",
    "period 1 special payments solvency deficiency members",
    "period 2 special payments solvency deficiency members",
    "period 3 special payments solvency deficiency members",
    "period 4 special payments solvency deficiency members",
    "special payments solvency deficiency present value",
    "period 1 special payments solvency deficiency employer",
    "period 2 special payments solvency deficiency employer",
    "period 3 special payments solvency deficiency employer",
    "period 4 special payments solvency deficiency employer",
    "special payments solvency deficiency present value",
    "solvency total asset value of buy in annuity",
    "solvency total liabilities buy in annuity",
    "solvency total asset value non discharged buy out annuity",
    "solvency total liabilities non discharged buy out annuity",
    "solvency liabilities related to discharge at time of purchase",
    "total value of reduced solvency deficiency payments guaranteed by letters of credit",
    "expiry date of letter of credit",
    "solvency asset adjustment",
    "solvency liability adjustment",
    "reduced liability adjustment",
    "solvency ratio as per regulations",
    "",
    "total amount of liabilities excluded",
    "",
    "",
    "amount solvency assets are adjusted averaging method",
    "change in method increases solvency asset adjustment",
    "change in method decreases solvency adjustment",
    "prior year credit balance pycb",
    "transfer ratio",
    "pbgf liabilities",
    "pbgf assessment base",
    "amount of additional liability for plan closure or permanent layoff benefits",
    "number of ontario plan beneficiaries",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "day of report",
    "month of report",
    "year of report",
    "actuary name",
    "name of firm",
    "actuary phone number",
    "actuary email address",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "this one 1 less than json",
    "",
    "",
    "variants:",
    "3, 14-17: start beginning",
    "4. date next valuation up until",
]

exclude = ["C003", "F006", "F0065", "F0067", "F0063", "F0062", "F0064", "F0066", "F006Other", "I020", "I021", "I20other", "I21other",
            "I036a", "I036ai", "l036aii", "I036aiii", "I036bi", "I036biim", "I036biif", "I037_includ",
            "I037_sep", "I037_no", "I038ai", "I038ae", "I038aei", "I038bi", "I038be", "I038bei", "I039", "I040", "I041",
            "K102", "K103", "L110", "M135", "M136", "M136a", "O137", "O138e", "O1391", "O1393", "O1394", "O1399a", "O1399b", "O141", "O144.(i)", "O144.(ii)"]

ratios = [273, 282]

rounding = [59, 64, 67, 126, 175]

dates = [3, 4]

dates_excl = [14, 15, 16, 17, 18, 19, 20, 21]

table_other = [105, 159, 161]

table_check = [104, 158, 160]

gc_mortality = ["A", "B", "C", "D", "E", "F", "G"]

solv_mortality = ["1994 UP Generational", "CPM2014Priv", "CPM2014", "CPM2014Publ"]
